version: 0.2

phases:
  install:
    commands:
      # Upgrade AWS CLI to the latest version; Install Leiningen; Install Clojure CLI tools
      - cd $HOME
      - pip install --upgrade awscli
      - wget https://raw.github.com/technomancy/leiningen/stable/bin/lein; chmod +x lein; mv lein /bin;
      - LEIN_ROOT=true lein
      - mkdir clj_tools_install; cd clj_tools_install
      - curl -O https://download.clojure.org/install/linux-install-1.10.0.411.sh; chmod +x linux-install-1.10.0.411.sh; ./linux-install-1.10.0.411.sh
      - cd $CODEBUILD_SRC_DIR
  pre_build:
    commands:
      - echo "\nContents of the base directory:\n"
      - ls -al
      - echo
      - echo Test started on `date`
      - LEIN_ROOT=true 
      - cd ./web-app
      - yarn --ignore-engines && yarn test
      - cd ../board-manager
      - lein test
      - cd $CODEBUILD_SRC_DIR
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mv ./infrastructure/board-manager/appspec.yml ./board-manager
      - mv ./infrastructure/board-manager/taskdef.json ./board-manager
      - mkdir ./board-manager/resources/public
      - cd ./web-app
      - yarn build && cp -R ./build/* ../board-manager/resources/public
      - cd ../board-manager 
      - lein uberjar
      - mv ./target/board-manager-0.1.0-SNAPSHOT-standalone.jar .
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 267892765183.dkr.ecr.us-west-2.amazonaws.com
      # - aws ecr get-login-password --region us-west-2 --profile rosenjcb | docker login --username AWS --password-stdin 267892765183.dkr.ecr.us-west-2.amazonaws.com
      - docker build -t conj .
      - docker tag conj:latest 267892765183.dkr.ecr.us-west-2.amazonaws.com/conj:latest 
      - docker push 267892765183.dkr.ecr.us-west-2.amazonaws.com/conj:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' conj-service 267892765183.dkr.ecr.us-west-2.amazonaws.com/conj:latest > imagedefinitions.json

artifacts:
  files:
    - 'imagedefinitions.json'
    - 'appspec.yml'
    - 'taskdef.json'
  base-directory: './board-manager/'
