version: '3.0'
services:
  redis:
    image: redis:alpine
    container_name: redis
  pepechan:
    depends_on:
      - redis
    build: ./board-manager/
    container_name: pepechan 
    image: 267892765183.dkr.ecr.us-west-2.amazonaws.com/pepechan
    environment:
      REDIS_HOST: redis
    ports:
      - "8080:8080"
