version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-2:HIDDEN:task-definition/conj:9"
        LoadBalancerInfo:
          ContainerName: "conj-container"
          ContainerPort: 8080 
